openapi: 3.0.0

info:
  title: "Strategic Organizational Restructuring API"
  description: "Analyzes legal staff data, calculates weighted merit scores, and generates restructuring reports."
  version: "1.0.0"

servers:
  - url: https://moodiest-uncontemptuously-cordell.ngrok-free.dev

paths:
  /generate-strategy:
    post:
      summary: "Process staff data and generate strategic report"
      operationId: "generateStrategy"
      description: "Accepts raw employee JSON, runs weighted scoring algorithms, ranks staff for HQ vs Remote, and identifies financial risks."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - employees
              properties:
                employees:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - rating
                      - talent
                      - studies
                      - salary
                      - job
                    properties:
                      employee_id:
                        oneOf:
                          - type: string
                          - type: integer
                        description: "employee ID (can be string or number)"
                        example: 101
                      name:
                        type: string
                        example: "Alice Sterling"
                      rating:
                        type: number
                        format: float
                        description: "Performance rating (0.0 - 5.0)"
                        example: 4.8
                      talent:
                        oneOf:
                          - type: string
                          - type: integer
                        description: "Talent assessment (High/Medium/Low or 1-5)"
                        example: 5
                      studies:
                        type: string
                        description: "Education level"
                        example: "PhD"
                      salary:
                        type: number
                        description: "Current annual salary"
                        example: 180000
                      job:
                        type: string
                        description: "Current Job Title"
                        example: "Senior Partner"
      responses:
        '200':
          description: "Report Generated Successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  statistics:
                    type: object
                    properties:
                      total_employees:
                        type: integer
                      average_merit_score:
                        type: number
                      hq_count:
                        type: integer
                      remote_count:
                        type: integer
                  strategic_report:
                    type: string
                    description: "The Markdown formatted text report generated by the LLM"
                  raw_algorithm_output:
                    type: object
                    description: "The raw JSON output from the Python ranking node"